export const plans = [
  {
    id: "esencial",
    badge: null,
    name: "Plan Esencial",
    tagline: "Perfecto para empezar a vender online",
    price: "S/ 299",
    priceNote: "pago único",
    highlight: false,
    color: "#4d82bc",
    accentBg: "#f0f6ff",
    features: [
      "Página web de hasta 10 productos",
      "Botón de WhatsApp en cada producto",
      "Diseño moderno adaptado a tu marca",
      "100% optimizada para celular",
      "Formulario de contacto",
      "Entrega en 2 a 5 días hábiles",
      "1 revisión de diseño incluida",
    ],
    notIncluded: [
      "Productos ilimitados",
      "Blog o sección de novedades",
      "Soporte prioritario",
    ],
    cta: "Empezar con Esencial",
  },
  {
    id: "pro",
    badge: "Más popular",
    name: "Plan Pro",
    tagline: "Para negocios que quieren destacar",
    price: "S/ 499",
    priceNote: "pago único",
    highlight: true,
    color: "#005187",
    accentBg: "#005187",
    features: [
      "Productos ilimitados",
      "Botón de WhatsApp en cada producto",
      "Diseño premium a medida",
      "100% optimizada para celular",
      "Formulario de contacto",
      "Entrega en 2 a 5 días hábiles",
      "3 revisiones de diseño incluidas",
      "Blog o sección de novedades",
      "Integración con redes sociales",
      "Soporte prioritario por 30 días",
    ],
    notIncluded: [],
    cta: "Empezar con Pro",
  },
];
